### ISSUE TITLE
[dunfell] some errors during unpack step in fossology server 

### ISSUE THREAD

**Issue by chaithubk** [fossology/fossology#1750]
I am able to successfully generate the SPDX docs for all `dunfell` `core-image-sato` packages except the below packages (one is at `do_compile`, but others failed at `do_spdx`).

Summary: 5 tasks failed:
```
  /home/yocto/output/poky/meta/recipes-gnome/gdk-pixbuf/gdk-pixbuf_2.40.0.bb:do_compile
  /home/yocto/output/poky/meta/recipes-core/gettext/gettext_0.20.1.bb:do_spdx
  /home/yocto/output/poky/meta/recipes-support/gnutls/gnutls_3.6.12.bb:do_spdx
  /home/yocto/output/poky/meta/recipes-support/libpsl/libpsl_0.21.0.bb:do_spdx
  /home/yocto/output/poky/meta/recipes-gnome/gnome/adwaita-icon-theme_3.34.3.bb:do_spdx
```

The error log for the above failures are below:

```
ERROR: gdk-pixbuf-2.40.0-r0 do_compile: Execution of '/home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/temp/run.do_compile.5144' failed with exit code 1:
[1/2] /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
FAILED: docs/gdk-pixbuf-csource.1 
/home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
ninja: build stopped: subcommand failed.
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/temp/log.do_compile.5144
Log data follows:
| DEBUG: Executing shell function do_compile
| [1/2] /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
| FAILED: docs/gdk-pixbuf-csource.1
| /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
| I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
| warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
| cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/temp/run.do_compile.5144' failed with exit code 1:
| [1/2] /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
| FAILED: docs/gdk-pixbuf-csource.1
| /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
| I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
| warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
| cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/home/yocto/output/poky/meta/recipes-gnome/gdk-pixbuf/gdk-pixbuf_2.40.0.bb:do_compile) failed with exit code '1'

-----------------------------------------------------------------------------------------------

ERROR: gettext-0.20.1-r0 do_spdx: Could not invoke scancode Command '/home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gettext/0.20.1-r0/recipe-sysroot-native/usr/bin/scancode -lpci --spdx-tv /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gettext/0.20.1-r0/spdx_sstate_dir/arm-poky-linux-gnueabi/gettext-0.20.1-r0/gettext-0.20.1.spdx /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gettext/0.20.1-r0/spdx_temp/' returned 1:
b'Setup plugins...\nCollect file inventory...\nScan files for: info, licenses, copyrights, packages with 1 process(es)...\nScanning done.\nSome files failed to scan properly:\nPath: spdx_temp/gettext-0.20.1/gettext-tools/misc/archive.dir.tar\nSummary:        info, licenses, copyrights, packages with 1 process(es)\nErrors count:   1\nScan Speed:     0.67 files/sec. 12.99 KB/sec.\nInitial counts: 6072 resource(s): 5835 file(s) and 237 directorie(s) \nFinal counts:   6072 resource(s): 5835 file(s) and 237 directorie(s) for 110.01 MB\nTimings:\n  scan_start: 2020-06-09T135951.126968\n  scan_end:   2020-06-09T162428.611805\n  setup_scan:licenses: 1.30s\n  setup: 1.30s\n  inventory: 1.93s\n  scan:packages: 0.49s\n  scan: 8672.24s\n  output:spdx-tv: 6.64s\n  output: 6.64s\n  total: 8684.54s\nRemoving temporary files...done.\n'
ERROR: Logfile of failure stored in: /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gettext/0.20.1-r0/temp/log.do_spdx.6774
ERROR: Task (/home/yocto/output/poky/meta/recipes-core/gettext/gettext_0.20.1.bb:do_spdx) failed with exit code '1'

-----------------------------------------------------------------------------------------------

ERROR: gnutls-3.6.12-r0 do_spdx: Could not invoke scancode Command '/home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gnutls/3.6.12-r0/recipe-sysroot-native/usr/bin/scancode -lpci --spdx-tv /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gnutls/3.6.12-r0/spdx_sstate_dir/arm-poky-linux-gnueabi/gnutls-3.6.12-r0/gnutls-3.6.12.spdx /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gnutls/3.6.12-r0/spdx_temp/' returned 1:
b'Setup plugins...\nCollect file inventory...\nScan files for: info, licenses, copyrights, packages with 1 process(es)...\nScanning done.\nSome files failed to scan properly:\nPath: spdx_temp/gnutls-3.6.12/tests/data/long.pem\nSummary:        info, licenses, copyrights, packages with 1 process(es)\nErrors count:   1\nScan Speed:     1.47 files/sec. 10.75 KB/sec.\nInitial counts: 6564 resource(s): 6456 file(s) and 108 directorie(s) \nFinal counts:   6564 resource(s): 6456 file(s) and 108 directorie(s) for 46.03 MB\nTimings:\n  scan_start: 2020-06-09T171835.506413\n  scan_end:   2020-06-09T183145.722364\n  setup_scan:licenses: 1.17s\n  setup: 1.17s\n  inventory: 1.88s\n  scan:packages: 0.52s\n  scan: 4384.91s\n  output:spdx-tv: 6.71s\n  output: 6.71s\n  total: 4397.42s\nRemoving temporary files...done.\n'
ERROR: Logfile of failure stored in: /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gnutls/3.6.12-r0/temp/log.do_spdx.30861
ERROR: Task (/home/yocto/output/poky/meta/recipes-support/gnutls/gnutls_3.6.12.bb:do_spdx) failed with exit code '1'

-------------------------------------------------------------------------------------------------

ERROR: libpsl-0.21.0-r0 do_spdx: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_spdx(d)
     0003:
File: '/home/yocto/output/poky/meta-spdxscanner/classes/scancode-tk.bbclass', lineno: 110, function: do_spdx
     0106:    if os.path.exists(git_path):
     0107:        remove_dir_tree(git_path)
     0108:    invoke_scancode(info['sourcedir'],sstatefile)
     0109:    bb.warn("source dir = " + info['sourcedir'])
 *** 0110:    if get_cached_spdx(sstatefile) != None:
     0111:        write_cached_spdx( info,sstatefile,cur_ver_code )
     0112:        ## CREATE MANIFEST(write to outfile )
     0113:        create_manifest(info,sstatefile)
     0114:    else:
File: '/home/yocto/output/poky/meta-spdxscanner/classes/spdx-common.bbclass', lineno: 164, function: get_cached_spdx
     0160:    except subprocess.CalledProcessError as e:
     0161:        bb.error("Index creation command '%s' failed with return code %d:\n%s" % (e.cmd, e.returncode, e.output))
     0162:        return None
     0163:    cached_spdx_info=output.decode('utf-8').split(': ')
 *** 0164:    return cached_spdx_info[1]
     0165:
     0166:#Find InfoInLicenseFile and fill into PackageLicenseInfoInLicenseFile.
     0167:def find_infoinlicensefile(sstatefile):
     0168:    import subprocess
Exception: IndexError: list index out of range

ERROR: Logfile of failure stored in: /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/libpsl/0.21.0-r0/temp/log.do_spdx.17370
ERROR: Task (/home/yocto/output/poky/meta/recipes-support/libpsl/libpsl_0.21.0.bb:do_spdx) failed with exit code '1'
-------------------------------------------------------------------------------------------------

ERROR: adwaita-icon-theme-3.34.3-r0 do_spdx: Could not invoke scancode Command '/home/yocto/output/build/tmp/work/all-poky-linux/adwaita-icon-theme/3.34.3-r0/recipe-sysroot-native/usr/bin/scancode -lpci --spdx-tv /home/yocto/output/build/tmp/work/all-poky-linux/adwaita-icon-theme/3.34.3-r0/spdx_sstate_dir/allarch-poky-linux/adwaita-icon-theme-3.34.3-r0/adwaita-icon-theme-3.34.3.spdx /home/yocto/output/build/tmp/work/all-poky-linux/adwaita-icon-theme/3.34.3-r0/spdx_temp/' returned 1:
b'Setup plugins...\nCollect file inventory...\nScan files for: info, licenses, copyrights, packages with 1 process(es)...\nScanning done.\nSome files failed to scan properly:\nPath: spdx_temp/adwaita-icon-theme-3.34.3/src/fullcolor/legacy/accessories-dictionary.svg\nSummary:        info, licenses, copyrights, packages with 1 process(es)\nErrors count:   1\nScan Speed:     0.88 files/sec. 31.42 KB/sec.\nInitial counts: 3178 resource(s): 3081 file(s) and 97 directorie(s) \nFinal counts:   3178 resource(s): 3081 file(s) and 97 directorie(s) for 107.63 MB\nTimings:\n  scan_start: 2020-06-10T194306.005261\n  scan_end:   2020-06-10T204137.397551\n  setup_scan:licenses: 1.45s\n  setup: 1.45s\n  inventory: 1.16s\n  scan:packages: 0.32s\n  scan: 3507.48s\n  output:spdx-tv: 7.24s\n  output: 7.24s\n  total: 3518.95s\nRemoving temporary files...done.\n'
ERROR: Logfile of failure stored in: /home/yocto/output/build/tmp/work/all-poky-linux/adwaita-icon-theme/3.34.3-r0/temp/log.do_spdx.15064
ERROR: Task (/home/yocto/output/poky/meta/recipes-gnome/gnome/adwaita-icon-theme_3.34.3.bb:do_spdx) failed with exit code '1'
```
And then, I uploaded this `adwaita-icon-theme-3.36.1.tar.xz` source code to fossology server manually, and I noticed these errors. 

```
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "ERROR: /srv/fossology/repository/f3aa05ad84e9/ununpack/932242l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/bd_double_arrow"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "Can not open the file as archive"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "ERROR: /srv/fossology/repository/f3aa05ad84e9/ununpack/932242l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/left_ptr_watch"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "Can not open the file as archive"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "ERROR: /srv/fossology/repository/f3aa05ad84e9/ununpack/932242l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/left_side"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "Can not open the file as archive"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "ERROR: /srv/fossology/repository/f3aa05ad84e9/ununpack/932242l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/hand1"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "Can not open the file as archive"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "ERROR: /srv/fossology/repository/f3aa05ad84e9/ununpack/932242l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/left_ptr_watch.ani"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "Can not open the file as archive"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "ERROR: /srv/fossology/repository/f3aa05ad84e9/ununpack/932242l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/target"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "Can not open the file as archive"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "ERROR: /srv/fossology/repository/f3aa05ad84e9/ununpack/932242l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/bottom_left_corner"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "Can not open the file as archive"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "ERROR: /srv/fossology/repository/f3aa05ad84e9/ununpack/932242l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/sb_h_double_arrow"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "Can not open the file as archive"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "ERROR: /srv/fossology/repository/f3aa05ad84e9/ununpack/932242l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/text"
2020-06-20 08:22:28 ununpack [0] :: JOB[2].ununpack[865.localhost]: "Can not open the file as archive"
```

**Comment by GMishx** [comment]
Can you please provide the mimetype of the failed files?

And do these error failed your upload?

**Comment by chaithubk** [comment]
These errors seems resolved now, and I got the spdx documents for all the above failed packages: 
```
 /home/yocto/output/poky/meta/recipes-core/gettext/gettext_0.20.1.bb:do_spdx
  /home/yocto/output/poky/meta/recipes-support/gnutls/gnutls_3.6.12.bb:do_spdx
  /home/yocto/output/poky/meta/recipes-support/libpsl/libpsl_0.21.0.bb:do_spdx
  /home/yocto/output/poky/meta/recipes-gnome/gnome/adwaita-icon-theme_3.34.3.bb:do_spdx
```

Am using meta-spdxscanner layer to generate the SPDX tag:value reports. Even manual upload worked fine on the portal. Don't know if there was any fix added now on the FOSSology side.

**Comment by GMishx** [comment]
Thank you for the logs @chaithubk.

I tried uploading the `adwaita-icon-theme-3.34.3.tar.xz` from web UI on FOSSology (latest master, on Debian 10) and the package got unpacked without much trouble except two files:

```
2020-07-09 11:20:05 ununpack [0] :: JOB[1966].ununpack[27894.localhost]: "ERROR: /srv/fossology/repository/neb/ununpack/287645l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/left_ptr_watch.ani"
2020-07-09 11:20:05 ununpack [0] :: JOB[1966].ununpack[27894.localhost]: "Can not open the file as archive"
2020-07-09 11:20:05 ununpack [0] :: JOB[1966].ununpack[27894.localhost]: "ERROR: /srv/fossology/repository/neb/ununpack/287645l/c1a26cdaceebebf87593d6780b2c92b7f20c9c84.9aea4ad9bc002aacad155ee0748b357f.19616468.dir/adwaita-icon-theme-3.34.3/Adwaita/cursors/watch.ani"
2020-07-09 11:20:05 ununpack [0] :: JOB[1966].ununpack[27894.localhost]: "Can not open the file as archive"
```

Error says that the agent could not unpack the files while treating them as archives. However, the files will still exist in the upload (as binary blobs) and if you really do not care much for them (from the logs, most failed files for you were `X11 cursor` files which will still work for copyright agent), you can ignore the log.

For your SPDX issue, I am not sure what happened there. As I've never used meta-spdxscanner, I would not be able to comment on that. However, we have done some fixes on the SPDX generation from FOSSology, that might have done the trick.

Do let us know if we could provide more help.

**Comment by chaithubk** [comment]
Thank you @GMishx
