### ISSUE TITLE
Edit in License Browser should not append equal events

### ISSUE THREAD

**Issue by steffen-weber** [fossology/fossology#458]
Deciderjob appended the "Add selected licenses" list as events and create decisions. But it should not include events if the latest decision already contains an equal event (same license, same scope). Issue #453 was one symptom of this bug.

**Comment by maximilianhuber** [comment]
Hi @steffen-weber,
is this issue already solved by the commit, which closed #453?

**Comment by steffen-weber** [comment]
No, commit daa0a68f28ec2d587a0e00924573b770d62ed3be fixed only the displayed count, but not the reason.
When licenseA was concluded for fileB and licenseA is also added with [Edit] in License Browser, then  an equal event (licenseA) is created and the deciderjob generates an equal conclusion. This can be seen in the Clearing History.

**Comment by shaheemazmalmmd** [comment]
WE(@EttingerK) have just tested this and see that the new decisions are getting added even though the same decision exists.

![Image](https://github.com/user-attachments/assets/6bbecc8f-6381-42e7-afed-66f8973e15f9)

**Comment by YashveerSingh123** [comment]
Hi @shaheemazmalmmd ,

I’d like to work on this issue.
 I’ll start by reproducing it on the latest Fossology version and then work on a fix so that equal events (same license and same scope) are not added again in the Clearing History.

Please let me know if this issue is still valid and if I can go ahead with it. Thanks.

**Comment by sakshammishra112** [comment]
Hi @shaheemazmalmmd,
I’ve reproduced the issue, and it’s still occurring. While working on this, I also encountered a similar issue related to the **global scope clearing decision**. Additionally, I’ve shared an enhancement suggestion with you on Slack. Once you approve, I’ll start working on it.

**Comment by shaheemazmalmmd** [comment]
@sakshammishra112 : thank you for the investigation you can start working on it.
